notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/gtag --watch=false
  - npx ng build @angeeks/gtag --prod
  - npx ng test gtag --watch=false
  - npx ng build gtag --prod --base-href gtag
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist/gtag
    github-token: $github
    skip-cleanup: true
    keep-history: true
