notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/gtag --watch=false
  - npx ng build @angeeks/gtag --prod
  - npx ng test gtag --watch=false
  - npx ng build gtag --prod --base-href gtag
cache:
    directories:
      - node_modules
before_deploy:
  - cp README.md dist/angeeks/gtag
  - cd dist/angeeks/gtag
deploy:
  - provider: npm
    email: $npmEmail
    api_key: $npm
    skip_cleanup: true
    keep-history: true
    tag: latest
    on:
      branch: release
